### ISSUE TITLE
TASKS LEFT TODO

### ISSUE THREAD

**Issue by afiffon** [avivnaaman/OpenU-C-Project#3]
## TODO
- [x]  1.1 Set IC=100, DC=0
- [x]  1.2 Read first line, skip to 1.17 if done
- [x]  1.3+1.4 Is symbol? set flag
- [x]  1.5+1.6 if .data or .string, store the symbol with DC in data table (error if already exists).
- [x]  1.7 encode the data into the data array,, andi increase DC by the length needed (increase by 1 for each data section (char/number))
- [x]  1.8+1.9+1.10 if extern, inert the symbol into extern table. read next line.
- [x]  1.11 otherwise, it's instruction. insert symbol if there's one to the code table
- [x]  1.12 check if it's valid command (like add, jmp..). if not, make sure an error is printed!
- [ ]  1.13 analyze the operand structure of the command
- [ ]  1.14 Build the binary code of the first instruction's word, and every other immediately-encoded data value (#)
- [ ]  1.15 Keep the values of L & IC for next stage
- [ ]  1.16 update IC=IC+L
- [ ]  1.17 Print any error f found and halt the program
- [ ]  1.18 Save IC as ICF and DC as DCF
- [ ]  1.19 Increase each .data value by ICF
- [ ]  1.20 Start 2nd pass

- [ ]  2.1 read next line, if done skip to 7
- [ ]  2.2 if label (symbol) skip
- [ ]  2.3+2.4+2.5 if entry, add it to entries table (only if exists in code table!)
- [ ]  2.6 complete replacement by symbols
- [ ]  2.7 stop and print errors
